sudo: required
language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
install:
  - npm install
before_script:
  - chmod +x ./scripts/travisBuild.sh
script: ./scripts/travisBuild.sh
