service: pluto-web-client

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  role: WebClientRole
  logRetentionInDays: 30
  apiGateway:
    minimumCompressionSize: 0
    binaryMediaTypes:
      - '*/*'

package:
  individually: true

functions:
  render:
    handler: ${file(./env/${opt:stage}.yml):HANDLER}
    memorySize: 2048
    timeout: 60
    package:
      artifact: dist.zip
    events:
      - http:
          method: any
          path: /
      - http:
          method: any
          path: /{proxy+}
resources:
  Resources:
    WebClientRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - edgelambda.amazonaws.com
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: SiteMapS3Role
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource: "arn:aws:s3:::scinapse-sitemap/*"
          - PolicyName: LambdaEdgeExecutionRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
          - PolicyName: XRayRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "xray:PutTraceSegments"
                    - "xray:PutTelemetryRecords"
                  Resource: "*"
          - PolicyName: LambdaMetricPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - cloudwatch:PutMetricData
                  Resource: "*"
          - PolicyName: SSMPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ssm:GetParameter
                  Resource: "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/scinapse-web-client/dev/branch-mapper"
