version: 2.1
orbs:
  slack: circleci/slack@3.2.0
jobs:
  deploy_to_dev:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:10
    environment:
      TZ: "Asia/Seoul"
    steps:
      - checkout
      - run:
          name: updating npm...
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
      - run:
          name: installing dev dependencies...
          command: npm ci
      - run: npm run test:ci
      - run: npm run deploy:dev
      - slack/notify:
          message: "Build DONE! $CIRCLE_BRANCH please check https://dev.scinapse.io?branch=$CIRCLE_BRANCH"
  deploy_to_stage:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:8.10
    environment:
      TZ: "Asia/Seoul"
    steps:
      - checkout
      - run:
          name: Set up puppeteer
          command: 'sh .circleci/setup_puppeteer.sh'
      - run:
          name: updating npm...
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
      - run:
          name: installing dev dependencies...
          command: npm ci
      - run: npm run test:ci
      - run: npm run deploy:stage
      - slack/notify:
          message: "Build DONE! $CIRCLE_BRANCH please check https://stage.scinapse.io"

  deploy_to_prod:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:8.10
    environment:
      TZ: "Asia/Seoul"
    steps:
      - checkout
      - run:
          name: Set up puppeteer
          command: 'sh .circleci/setup_puppeteer.sh'
      - run:
          name: updating npm...
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
      - run:
          name: installing dev dependencies...
          command: npm ci
      - run: npm run test:ci
      - run: npm run deploy:prod
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export DEPLOYED_VERSION=$(cat ./version)' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Update commit messages and Define Environment Variable at Runtime
          command: |
            echo 'export COMMIT_MESSAGES=$(git log --oneline --pretty=format:"%cd(%cr)] <https://github.com/pluto-net/scinapse-web-client/commit/%H|%s> - (By %an)" production..HEAD)' >> $BASH_ENV
            source $BASH_ENV
      - slack/notify:
          webhook: $DEPLOY_PROD_SLACK_WEBHOOK
          message: $COMMIT_MESSAGES
      - run:
          name: set git tag
          command: |
            git config --global user.email "dev@pluto.network"
            git config --global user.name "CircleCI"
            git tag production -f
            git push https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/pluto-net/scinapse-web-client.git --tags -f
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_dev:
          filters:
            branches:
              ignore:
                - master
                - stage
      - deploy_to_stage:
          filters:
            branches:
              only:
                - stage
      - deploy_to_prod:
          filters:
            branches:
              only:
                - hotfix
                - master
