version: 2
jobs:
  deploy_to_dev:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:ci
      - run: npm run deploy:dev
  deploy_to_prod:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:ci
      - run: npm run deploy:prod
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_dev:
          filters:
            branches:
              ignore: master
      - deploy_to_prod:
          filters:
            branches:
              only: master
