version: 2.1
orbs:
  slack: circleci/slack@2.5.0
jobs:
  deploy_to_dev:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:ci
      - run: npm run deploy:dev
      - slack/notify:
          message: "Build DONE! $CIRCLE_BRANCH please check https://dev.scinapse.io?branch=$CIRCLE_BRANCH"
  deploy_to_prod:
    working_directory: ~/scinapse
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:ci
      - run: npm run deploy:prod
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_dev:
          filters:
            branches:
              ignore: master
      - deploy_to_prod:
          filters:
            branches:
              only: master
