HANDLER: handler.ssr
NEW_RELIC_NO_CONFIG_FILE: true
NEW_RELIC_APP_NAME: scinapse-web-client-dev
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
NEW_RELIC_ACCOUNT_ID: 2462269
NEW_RELIC_PRIMARY_APPLICATION_ID: 2462269
NEW_RELIC_TRUSTED_ACCOUNT_KEY: 2462269

